name: post_pull_request
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  playground:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Dump GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Dump GitHub Event
        run: cat "${GITHUB_EVENT_PATH}"

      - name: Dump Env
        run: env

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: CI.yml
          commit: ${{ github.event.workflow_run.head_commit.id }}
          name: built-site
          path: built

      - run: ls
      - run: echo "-"
      - run: ls built

      - name: "Make a fake 'app' for the azure project of the static HTML"
        run: |
          echo '{ "name": "fake", "scripts": { "build": "" } }' > built/package.json

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MEADOW_0C9756810 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "built" # App source code path
          ###### End of Repository/Build Configurations ######

      - if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
          - name: Close Pull Request
            id: closepullrequest
            uses: Azure/static-web-apps-deploy@v0.0.1-preview
            with:
              azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_MEADOW_0C9756810 }}
              action: "close"

      # danger for PR builds
      - run: "danger ci"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
