name: "PR Checks"
on: [pull_request]


jobs:
  build:
    name: "Builds and Deploys"
    runs-on: ubuntu-latest

    steps:
    # Check out, and set up the node/ruby infra
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-node@v1
    - uses: actions/setup-ruby@v1

    # Get all the local deps, then run danger
    - run: yarn install
    - run: yarn danger ci
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Now try build the site
    - run: cd src/play; yarn install; yarn setup; cd ../..
    - run: bundle install
    - run: gulp publish

    # Deploy if we can
    - run: '[ -z "$NOW_ACCESS_TOKEN" ] && echo "Skipping deploy" || npx now site/ --token=$NOW_ACCESS_TOKEN --name=typescript-site-$PR_NUMBER'
      env:
        NOW_ACCESS_TOKEN: ${{ secrets.NOW_ACCESS_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}

