name: Build Website To Staging

on:
  push:
    branches: [v2]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      # For Azure uploads
      - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Prepare website v2
        run: |
          yarn install
          yarn docs-sync pull microsoft/TypeScript-Website-localizations#main 1
          yarn bootstrap
          yarn build
        env:
          YARN_CHECKSUM_BEHAVIOR: ignore

      - name: Build website v2
        run: |
          yarn build-site
          cp -r packages/typescriptlang-org/public site
        env:
          GATSBY_TYPESCRIPT_SITE_STAGING: true

      - name: Deploy + Publish to CDN
        # You can find these keys here:
        # https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/57bfeeed-c34a-4ffd-a06b-ccff27ac91b8/resourcegroups/typescriptlang-org/providers/Microsoft.Storage/storageAccounts/typescriptorgstaging/keys
        env:
          AZURE_STORAGE_ACCOUNT: "typescriptorgstaging"
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_CDN_STAGING_CONNECTION_STRING }}
        run: az storage blob upload-batch -s ./site -d \$web

      # Deploy
      - name: Deploy npm Packages
        run: |
          yarn pleb publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

      - name: Send a message to Microsoft Teams
        if: ${{ failure() }}
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEB_BOT_INCOMING_URL }}
          title: Staging deploy failed
          summary: Could not build the site for staging
          actions: '[{ "@type": "OpenUri", "name": "View Logs", "targets": [{ "os": "default", "uri": "https://github.com/microsoft/TypeScript-Website/actions/runs/${{ github.run_id }}?check_suite_focus=true" }] }]'
