name: Build Website To Staging

on:
  push:
    branches: [v2]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out, and set up the node/ruby infra
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org/"

      # For Azure uploads
      - run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Build v2
      - name: Build website v2
        run: |
          yarn install
          yarn bootstrap
          yarn build
          yarn build-site
          cp -r packages/typescriptlang-org/public site

      - name: Send a message to Microsoft Teams
        if: failure()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook-uri: ${{ secrets.TEAMS_WEB_BOT_INCOMING_URL }}
          title: Staging build failed
          summary: Could not build the site for staging

      - name: Deploy + Publish to CDN
        # You can find these keys here:
        # https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/57bfeeed-c34a-4ffd-a06b-ccff27ac91b8/resourcegroups/typescriptlang-org/providers/Microsoft.Storage/storageAccounts/typescriptorgstaging/keys
        env:
          AZURE_STORAGE_ACCOUNT: "typescriptorgstaging"
          AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_CDN_STAGING_CONNECTION_STRING }}
        run: az storage blob upload-batch -s ./site -d \$web

      # CI: Deploy to the right branch to trigger the deploy to the AppService site
      - name: Deploy + Publish to AppService
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: "SITE-STAGING"
          PUBLISH_DIR: ./site

      # Deploy
      - name: Deploy npm Packages
        run: |
          yarn pleb publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
